### ISSUE TITLE
Config object is built in each request

### ISSUE THREAD

**Issue by devgar** [UlisesGascon/express-simple-pagination#4]
Hi! As titled, the config is built inside the request handler. This makes building it in each request.
```javascript
module.exports = (configProvided = {}) => (req, res, next) => {
  const config = { min: 20, max: 500, ...configProvided }
  req.pagination = {
  ···
```
The config generation is pretty short just now but must be avoided.
I propose replacing it like this
```javascript
module.exports = (configProvided = {}) => {
  const config = { min: 20, max: 500, ...configProvided }
  return (req, res, next) => {
    req.pagination = {
    ···
```

**Comment by UlisesGascon** [comment]
Hi @devgar ! Thanks for this suggestion. I will check the PR #5 and create a new release with it 👾
