### ISSUE TITLE
Add behaviour to handle `page`query argument

### ISSUE THREAD

**Issue by devgar** [UlisesGascon/express-simple-pagination#6]
This is an enchancement suggestion.

A lot of Apps doesn't use offset nor limt, them just use `page` as pagination variable. I propose to handle this argument.

Page value will modify the offset by the rule `offset = page * limit`. Due this, the page should be ignored if `offset` isn't 0.

Page will be parsed but it could be not included in the pagination resulting object. For most query purposses page is unnecessary besides offest and limit. By the other hand is just more info.

About validation.
Page must be number, integer and positive.

**Comment by UlisesGascon** [comment]
Sounds good to me. Do you want to do an implementation? :)

**Comment by devgar** [comment]
Yes! My pull request will come.

**Comment by UlisesGascon** [comment]
Released in `express-simple-pagination@1.1.0`
